name: Feature Request
description: Create a feature request.
title: "[FR]: "
labels: ["feature"]
#projects: ["octo-org/1", "octo-org/44"]
type: "Feature"
assignees:
  - "@me"
body:
  - type: markdown
    attributes:
      value: |
        ThankS for taking the time to submit a feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-would-you-like-see
    attributes:
      label: What would you like to see added?
      description: Please describe the feature you'd like to see added in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: how-could-it-help-you
    attributes:
      label: How would this help you day to day? 
      description: Please describe how this feature would help you in as much detail as possible.
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: How important is this feature to you?
      multiple: false
      options:
        - Not necessary (for now)
        - Nice to have, optional
        - Highly desirable, very important
        - Non-negotiable, primary need 
    validations:
      required: true